### PR TITLE
Avoid duplicate subs in qlobber

### PR DESCRIPTION
**Pull request by GavinDmello**
Related to <a>https://github.com/mcollina/aedes-persistence/pull/8#<a/> 
I think a utility function which can be used in both should be great.

### CODE REVIEW

**Comment by mcollina** [comment]
Do you think we'll need this somewhere else?
The function is not very complicated, I fear we are putting too much code in the abstract ones.

**Comment by GavinDmello** [comment]
@mcollina Probably not, We're using cached persistence in all the persistences except memory.
We could've made a  util file and required the function from there as cached persistence has aedes persistence as a dep.

**Comment by GavinDmello** [comment]
I think let's merge this, I'll add a common function if I see a use case somewhere

**Comment by mcollina** [comment]
@GavinDmello this is failing with the just-released version of aedes:

# add duplicate subs to persistence for qos 0
ok 65 client must be the same
ok 66 no error
ok 67 client must be the same
ok 68 no error
ok 69 no error
not ok 70 should be equivalent
  ---
    operator: deepEqual
    expected: |-
      [ { qos: 0, topic: 'hello' } ]
    actual: |-
      [ { qos: 0, topic: 'hello' }, { qos: 0, topic: 'hello' } ]
    at: MyPersistence.MemoryPersistence.subscriptionsByClient (/Users/matteo/Repositories/aedes-cached-persistence/node_modules/aedes-persistence/persistence.js:144:3)
  ...

**Comment by GavinDmello** [comment]
Let me check

**Comment by GavinDmello** [comment]
Works at my end.

**Comment by mcollina** [comment]
Have a look at: https://travis-ci.org/mcollina/aedes-cached-persistence/builds/211269515.
Try `rm -rf node_modules`.

**Comment by GavinDmello** [comment]
We're using a different persistence addSubscription function for this ? https://github.com/mcollina/aedes-cached-persistence/blob/master/test.js#L39. That's adding the sub twice. I think

**Comment by mcollina** [comment]
would you mind to send a PR to fix this as well?

**Pull request merged**
